title: Kaibing YAng's Homepage
page-top-title: Kaibing Yang
top-section-bg-text: Artificial Intelligence
home-subtitle: Kaibing Yang&enfp;|&ensp;杨凯冰
copyright-text: '&copy; Kaibing Yang 2024-2025. All Rights Reserved.'
